export const APP_NAME = "QuickFlip";
export const QUICKFLIP_APP_ID = "109";

export const QUICKFLIP_CONTRACT_ADDRESS =
  "0x522c8979B2613b35b3FB22CBEcda1ee34C019198" as const;

// Placeholders kept explicitly for future replacement.
export const QUICKFLIP_CONTRACT_ADDRESS_PLACEHOLDER =
  "QUICKFLIP_CONTRACT_ADDRESS_PLACEHOLDER";
export const BASE_APP_ID_PLACEHOLDER = "BASE_APP_ID_PLACEHOLDER";
export const TALENT_VERIFICATION_PLACEHOLDER =
  "TALENT_VERIFICATION_PLACEHOLDER";
export const QUICKFLIP_APP_ID_PLACEHOLDER = "QUICKFLIP_APP_ID_PLACEHOLDER";
export const BUILDER_CODE_PLACEHOLDER = "BUILDER_CODE_PLACEHOLDER";
export const GITHUB_TOKEN_PLACEHOLDER = "GITHUB_TOKEN_PLACEHOLDER";
export const VERCEL_TOKEN_PLACEHOLDER = "VERCEL_TOKEN_PLACEHOLDER";

export const QUICKFLIP_BUILDER_CODE = "bc_hots2jvt";
export const QUICKFLIP_BUILDER_DATA_SUFFIX =
  "0x62635f686f7473326a76740b0080218021802180218021802180218021";
